Ext.ns("Thang.view");

Thang.view.Main=Ext.extend(Ext.Panel,{
    
    constructor:function(config){
    	config=config||{};
    	Ext.apply(this,config,this.config);
    	Thang.view.Main.superclass.constructor.call(this);
    },
    config:{// main panel with header tab
	        xtype:'panel',
	        region:'center',
			layout:'card',
			activeItem:0,
			tbar:[{
				     id:'home',
					 scale:'large',
				     width:110,
				     height:45,
					 toggleGroup:'navigation',
				     text:Ext.bigFont('首页',15,true),
				     icon:'../tools/icons/home.png',
					 handler:function(btn,evt){
						Ext.getCmp('mainView').layout.setActiveItem(0);
					}
				   },'-',
				  {
					 text:Ext.bigFont('办公管理',15,false),
					 icon:'../tools/icons/work.png',
					 width:110,
					 height:45,
					 scale:'large',
					 id:'office',
					 toggleGroup:'navigation',
					 menu:{items:[{
								     id:'incept',
						             text:Ext.bigFont('收文管理',14,false),
									 iconCls:'icon-folder_table'
								    },{
									 id:'insend',
									 text:Ext.bigFont('发文管理',14,false),
									 iconCls:'icon-folder_up'
								   }]
					},//menu end
					handler:function(btn,evt){
						Ext.getCmp('mainView').layout.setActiveItem(1);
					}
					 
				   },'-',
				{
					 id:'person',
					 text:Ext.bigFont('人事管理',15,false),
					 icon:'../tools/icons/person.png',
					 width:110,
					 height:45,
					 scale:'large',
					 toggleGroup:'navigation',
					 handler:function(btn,evt){
					 	Ext.getCmp('mainView').layout.setActiveItem(2);
					 }
				   },'-',
				{
					 id:'info',
					 text:Ext.bigFont('信息发布',15,false),
					 icon:'../tools/icons/info.png',
					 width:110,
					 height:45,
					 scale:'large',
					 toggleGroup:'navigation',
					 handler:function(btn,evt){
					 	Ext.getCmp('mainView').layout.setActiveItem(3);
					 }
				   },'-',
				{
					 id:'archive',
					 text:Ext.bigFont('档案管理',15,false),
					 icon:'../tools/icons/archive.png',
					 width:110,
					 height:45,
					 scale:'large',
					 toggleGroup:'navigation',
					 handler:function(btn,evt){
					 	Ext.getCmp('mainView').layout.setActiveItem(4);
					 }
				   },'-',
				 {
					 id:'system',
					 text:Ext.bigFont('系统设置',15,false),
					 icon:'../tools/icons/tools.png',
					 width:110,
					 height:45,
					 scale:'large',
					 toggleGroup:'navigation',
					 handler:function(btn,evt){
					 	Ext.getCmp('mainView').layout.setActiveItem(5);
					 }
				   },'->',
				{
					 text:Ext.bigFont('退出',15,true),
					 icon:'../tools/icons/logout.png',
					 width:110,
					 height:45,
					 scale:'large',
					 handler:function(btn,evt){
						 window.location.href="logout";
					 }
				}]//tbar end
	      
	}//config end

});